id: IC503D49C
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-18T23:57:03.173854'
last_modified: '2022-06-18T23:57:03.173867'
parser: null
source_metadata:
  title: A mes zhabss (1597–1659) Exposition on the Lamdre Practice according to the
    Ngor pa and rDzong pa
  author: a myes zhabs ngag dbang kun dga bsod nams/
  description: 'Digital version 2.0 {Wylie}; WYLIE COPY of master xml (completed:
    2015-07-12); unrevised, no thematic TEI markup'
  file_info:
  - 'Language: Wylie'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:Sakya Research Centre (src)
  - Text input:Guru Lama, Sachen International, Kathmandu (Nepal) (si)
  - Editorial process:Mathias Fermer (mf), byams pa chos dbang / (Dehradun) (jc)
  - TEI Encoding:Sakya Research Centre
  - TEI Markup:-
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/967
  bases:
    211b:
      title: A mes zhabss (1597–1659) Exposition on the Lamdre Practice according
        to the Ngor pa and rDzong pa
      order: 1
      base_file: 211b.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
